# Generated by Django 3.0 on 2019-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devfest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
